package sdk.pendo.io.u3;

import androidx.exifinterface.media.ExifInterface;
import sdk.pendo.io.m3.v;

/* loaded from: classes3.dex */
public interface b {
    public static final v A;
    public static final v B;
    public static final v C;
    public static final v D;
    public static final v E;
    public static final v F;
    public static final v G;
    public static final v H;
    public static final v I;
    public static final v J;
    public static final v K;
    public static final v L;
    public static final v M;
    public static final v N;
    public static final v O;
    public static final v P;
    public static final v Q;
    public static final v R;
    public static final v S;
    public static final v T;
    public static final v U;
    public static final v V;
    public static final v W;
    public static final v X;
    public static final v Y;
    public static final v Z;

    /* renamed from: a, reason: collision with root package name */
    public static final v f1640a;
    public static final v a0;
    public static final v b;
    public static final v b0;
    public static final v c;
    public static final v c0;
    public static final v d;
    public static final v d0;
    public static final v e;
    public static final v e0;
    public static final v f;
    public static final v f0;
    public static final v g;
    public static final v g0;
    public static final v h;
    public static final v h0;
    public static final v i;
    public static final v i0;
    public static final v j;
    public static final v j0;
    public static final v k;
    public static final v k0;
    public static final v l;
    public static final v l0;
    public static final v m;
    public static final v m0;
    public static final v n;
    public static final v o;
    public static final v p;
    public static final v q;
    public static final v r;
    public static final v s;
    public static final v t;
    public static final v u;
    public static final v v;
    public static final v w;
    public static final v x;
    public static final v y;
    public static final v z;

    static {
        v vVar = new v("1.2.156.10197.1");
        f1640a = vVar;
        b = vVar.b("101.1");
        c = vVar.b("101.2");
        d = vVar.b("101.3");
        e = vVar.b("101.4");
        f = vVar.b("102.1");
        g = vVar.b("102.2");
        h = vVar.b("102.3");
        i = vVar.b("102.4");
        j = vVar.b("102.5");
        k = vVar.b("102.6");
        l = vVar.b("103.1");
        m = vVar.b("103.2");
        n = vVar.b("103.3");
        o = vVar.b("103.4");
        p = vVar.b("103.5");
        q = vVar.b("103.6");
        r = vVar.b("104.1");
        s = vVar.b("104.2");
        t = vVar.b("104.3");
        u = vVar.b("104.4");
        v = vVar.b("104.5");
        w = vVar.b("104.6");
        x = vVar.b("104.7");
        y = vVar.b("104.8");
        z = vVar.b("104.9");
        A = vVar.b("104.10");
        B = vVar.b("104.11");
        C = vVar.b("104.12");
        D = vVar.b("104.100");
        E = vVar.b("201");
        F = vVar.b("301");
        G = vVar.b("301.1");
        H = vVar.b("301.2");
        v b2 = vVar.b("301.3");
        I = b2;
        J = vVar.b("301.101");
        K = b2.b("1");
        L = b2.b(ExifInterface.GPS_MEASUREMENT_2D);
        M = b2.b("2.1");
        N = b2.b("2.2");
        O = b2.b("2.3");
        P = b2.b("2.4");
        Q = b2.b("2.5");
        R = b2.b("2.6");
        S = b2.b("2.7");
        T = b2.b("2.8");
        U = b2.b("2.9");
        V = b2.b("2.10");
        W = b2.b("2.11");
        X = vVar.b("302");
        Y = vVar.b("302.1");
        Z = vVar.b("302.2");
        a0 = vVar.b("302.3");
        v b3 = vVar.b("401");
        b0 = b3;
        c0 = b3.b(ExifInterface.GPS_MEASUREMENT_2D);
        d0 = vVar.b("501");
        e0 = vVar.b("502");
        f0 = vVar.b("503");
        g0 = vVar.b("504");
        h0 = vVar.b("505");
        i0 = vVar.b("506");
        j0 = vVar.b("507");
        k0 = vVar.b("520");
        l0 = vVar.b("521");
        m0 = vVar.b("522");
    }
}
