package sdk.pendo.io.y3;

import androidx.exifinterface.media.ExifInterface;
import sdk.pendo.io.m3.v;

/* loaded from: classes4.dex */
public interface a {
    public static final v A;
    public static final v A0;
    public static final v A1;
    public static final v B;
    public static final v B0;
    public static final v B1;
    public static final v C;
    public static final v C0;
    public static final v C1;
    public static final v D;
    public static final v D0;
    public static final v D1;
    public static final v E;
    public static final v E0;
    public static final v E1;
    public static final v F;
    public static final v F0;
    public static final v F1;
    public static final v G;
    public static final v G0;
    public static final v G1;
    public static final v H;
    public static final v H0;
    public static final v H1;
    public static final v I;
    public static final v I0;
    public static final v I1;
    public static final v J;
    public static final v J0;
    public static final v J1;
    public static final v K;
    public static final v K0;
    public static final v K1;
    public static final v L;
    public static final v L0;
    public static final v L1;
    public static final v M;
    public static final v M0;
    public static final v M1;
    public static final v N;
    public static final v N0;
    public static final v N1;
    public static final v O;
    public static final v O0;
    public static final v O1;
    public static final v P;
    public static final v P0;
    public static final v P1;
    public static final v Q;
    public static final v Q0;
    public static final v Q1;
    public static final v R;
    public static final v R0;
    public static final v R1;
    public static final v S;
    public static final v S0;
    public static final v S1;
    public static final v T;
    public static final v T0;
    public static final v T1;
    public static final v U;
    public static final v U0;
    public static final v U1;
    public static final v V;
    public static final v V0;
    public static final v V1;
    public static final v W;
    public static final v W0;
    public static final v W1;
    public static final v X;
    public static final v X0;
    public static final v Y;
    public static final v Y0;
    public static final v Z;
    public static final v Z0;

    /* renamed from: a, reason: collision with root package name */
    public static final v f1764a;
    public static final v a0;
    public static final v a1;
    public static final v b;
    public static final v b0;
    public static final v b1;
    public static final v c;
    public static final v c0;
    public static final v c1;
    public static final v d;
    public static final v d0;
    public static final v d1;
    public static final v e;
    public static final v e0;
    public static final v e1;
    public static final v f;
    public static final v f0;
    public static final v f1;
    public static final v g;
    public static final v g0;
    public static final v g1;
    public static final v h;
    public static final v h0;
    public static final v h1;
    public static final v i;
    public static final v i0;
    public static final v i1;
    public static final v j;
    public static final v j0;
    public static final v j1;
    public static final v k;
    public static final v k0;
    public static final v k1;
    public static final v l;
    public static final v l0;
    public static final v l1;
    public static final v m;
    public static final v m0;
    public static final v m1;
    public static final v n;
    public static final v n0;
    public static final v n1;
    public static final v o;
    public static final v o0;
    public static final v o1;
    public static final v p;
    public static final v p0;
    public static final v p1;
    public static final v q;
    public static final v q0;
    public static final v q1;
    public static final v r;
    public static final v r0;
    public static final v r1;
    public static final v s;
    public static final v s0;
    public static final v s1;
    public static final v t;
    public static final v t0;
    public static final v t1;
    public static final v u;
    public static final v u0;
    public static final v u1;
    public static final v v;
    public static final v v0;
    public static final v v1;
    public static final v w;
    public static final v w0;
    public static final v w1;
    public static final v x;
    public static final v x0;
    public static final v x1;
    public static final v y;
    public static final v y0;
    public static final v y1;
    public static final v z;
    public static final v z0;
    public static final v z1;

    static {
        v vVar = new v("1.2.840.113549.1.1");
        f1764a = vVar;
        b = vVar.b("1");
        c = vVar.b(ExifInterface.GPS_MEASUREMENT_2D);
        d = vVar.b(ExifInterface.GPS_MEASUREMENT_3D);
        e = vVar.b("4");
        f = vVar.b("5");
        g = vVar.b("6");
        h = vVar.b("7");
        i = vVar.b("8");
        j = vVar.b("9");
        k = vVar.b("10");
        l = vVar.b("11");
        m = vVar.b("12");
        n = vVar.b("13");
        o = vVar.b("14");
        p = vVar.b("15");
        q = vVar.b("16");
        v vVar2 = new v("1.2.840.113549.1.3");
        r = vVar2;
        s = vVar2.b("1");
        v vVar3 = new v("1.2.840.113549.1.5");
        t = vVar3;
        u = vVar3.b("1");
        v = vVar3.b("4");
        w = vVar3.b(ExifInterface.GPS_MEASUREMENT_3D);
        x = vVar3.b("6");
        y = vVar3.b("10");
        z = vVar3.b("11");
        A = vVar3.b("12");
        B = vVar3.b("13");
        C = vVar3.b("14");
        v vVar4 = new v("1.2.840.113549.3");
        D = vVar4;
        E = vVar4.b("7");
        F = vVar4.b(ExifInterface.GPS_MEASUREMENT_2D);
        G = vVar4.b("4");
        v vVar5 = new v("1.2.840.113549.2");
        H = vVar5;
        I = vVar5.b(ExifInterface.GPS_MEASUREMENT_2D);
        J = vVar5.b("4");
        K = vVar5.b("5");
        L = vVar5.b("7").m();
        M = vVar5.b("8").m();
        N = vVar5.b("9").m();
        O = vVar5.b("10").m();
        P = vVar5.b("11").m();
        Q = vVar5.b("12").m();
        R = vVar5.b("13").m();
        S = new v("1.2.840.113549.1.7").m();
        T = new v("1.2.840.113549.1.7.1").m();
        U = new v("1.2.840.113549.1.7.2").m();
        V = new v("1.2.840.113549.1.7.3").m();
        W = new v("1.2.840.113549.1.7.4").m();
        X = new v("1.2.840.113549.1.7.5").m();
        Y = new v("1.2.840.113549.1.7.6").m();
        v vVar6 = new v("1.2.840.113549.1.9");
        Z = vVar6;
        a0 = vVar6.b("1").m();
        b0 = vVar6.b(ExifInterface.GPS_MEASUREMENT_2D).m();
        c0 = vVar6.b(ExifInterface.GPS_MEASUREMENT_3D).m();
        d0 = vVar6.b("4").m();
        e0 = vVar6.b("5").m();
        f0 = vVar6.b("6").m();
        g0 = vVar6.b("7").m();
        h0 = vVar6.b("8").m();
        i0 = vVar6.b("9").m();
        j0 = vVar6.b("13").m();
        k0 = vVar6.b("14").m();
        l0 = vVar6.b("15").m();
        v m2 = vVar6.b("16").m();
        m0 = m2;
        n0 = vVar6.b("16.2.46").m();
        o0 = vVar6.b("20").m();
        p0 = vVar6.b("21").m();
        q0 = vVar6.b("22.1");
        v b2 = vVar6.b("22");
        r0 = b2;
        s0 = b2.b("1").m();
        t0 = b2.b(ExifInterface.GPS_MEASUREMENT_2D).m();
        v b3 = vVar6.b("23");
        u0 = b3;
        v0 = b3.b("1").m();
        w0 = vVar6.b("52").m();
        x0 = vVar6.b("15.1");
        y0 = vVar6.b("15.2");
        z0 = vVar6.b("15.3");
        v vVar7 = new v("1.2.840.113549.1.9.16.1");
        A0 = vVar7;
        B0 = vVar7.b(ExifInterface.GPS_MEASUREMENT_2D);
        C0 = vVar7.b("4");
        D0 = vVar7.b("9");
        E0 = vVar7.b("23");
        F0 = vVar7.b("31");
        v b4 = m2.b(ExifInterface.GPS_MEASUREMENT_3D);
        G0 = b4;
        H0 = b4.b("9");
        I0 = b4.b("14");
        J0 = b4.b("17");
        K0 = b4.b("18");
        L0 = b4.b("28");
        M0 = b4.b("29");
        N0 = b4.b("30");
        v vVar8 = new v("1.2.840.113549.1.9.16.6");
        O0 = vVar8;
        P0 = vVar8.b("1");
        Q0 = vVar8.b(ExifInterface.GPS_MEASUREMENT_2D);
        R0 = vVar8.b(ExifInterface.GPS_MEASUREMENT_3D);
        S0 = vVar8.b("4");
        T0 = vVar8.b("5");
        U0 = vVar8.b("6");
        v vVar9 = new v("1.2.840.113549.1.9.16.2");
        V0 = vVar9;
        W0 = vVar9.b("1");
        X0 = vVar9.b("4");
        Y0 = vVar9.b("5");
        Z0 = vVar9.b("10");
        a1 = vVar9.b("11");
        b1 = vVar9.b("12");
        c1 = vVar9.b("47");
        d1 = vVar9.b("7");
        e1 = vVar9.b("14");
        v b5 = vVar9.b("15");
        f1 = b5;
        v b6 = vVar9.b("16");
        g1 = b6;
        v b7 = vVar9.b("17");
        h1 = b7;
        i1 = vVar9.b("18");
        v b8 = vVar9.b("19");
        j1 = b8;
        k1 = vVar9.b("20");
        l1 = vVar9.b("21");
        m1 = vVar9.b("22");
        n1 = vVar9.b("23");
        o1 = vVar9.b("24");
        p1 = vVar9.b("25");
        q1 = vVar9.b("26");
        r1 = vVar9.b("27");
        s1 = vVar9.b("37");
        t1 = vVar9.b("38");
        u1 = vVar9.b("54");
        v1 = vVar9.b("43");
        w1 = vVar9.b("40");
        x1 = b5;
        y1 = b6;
        z1 = b7;
        A1 = b8;
        B1 = new v("1.2.840.113549.1.9.16.5.1");
        C1 = new v("1.2.840.113549.1.9.16.5.2");
        v vVar10 = new v("1.2.840.113549.1.12");
        D1 = vVar10;
        v b9 = vVar10.b("10.1");
        E1 = b9;
        F1 = b9.b("1");
        G1 = b9.b(ExifInterface.GPS_MEASUREMENT_2D);
        H1 = b9.b(ExifInterface.GPS_MEASUREMENT_3D);
        I1 = b9.b("4");
        J1 = b9.b("5");
        K1 = b9.b("6");
        v b10 = vVar10.b("1");
        L1 = b10;
        M1 = b10.b("1");
        N1 = b10.b(ExifInterface.GPS_MEASUREMENT_2D);
        O1 = b10.b(ExifInterface.GPS_MEASUREMENT_3D);
        P1 = b10.b("4");
        Q1 = b10.b("5");
        R1 = b10.b("6");
        S1 = b10.b("6");
        T1 = new v("1.2.840.113549.1.9.16.3.6");
        U1 = new v("1.2.840.113549.1.9.16.3.7");
        V1 = new v("1.2.840.113549.1.9.16.3.5");
        W1 = new v("1.2.840.113549.1.9.16.3.10");
    }
}
