package sdk.pendo.io.f4;

import androidx.exifinterface.media.ExifInterface;
import sdk.pendo.io.m3.v;

/* loaded from: classes6.dex */
public interface h {
    public static final v B;
    public static final v C;
    public static final v D;
    public static final v E;
    public static final v F;
    public static final v G;
    public static final v H;
    public static final v I;
    public static final v J;
    public static final v K;
    public static final v L;
    public static final v M;
    public static final v N;
    public static final v O;
    public static final v P;
    public static final v Q;
    public static final v R;
    public static final v S;
    public static final v T;
    public static final v U;
    public static final v V;
    public static final v W;
    public static final v X;
    public static final v Y;
    public static final v Z;

    /* renamed from: a, reason: collision with root package name */
    public static final v f1079a;
    public static final v a0;
    public static final v b;
    public static final v b0;
    public static final v c;
    public static final v c0;
    public static final v d;
    public static final v d0;
    public static final v e;
    public static final v e0;
    public static final v g;
    public static final v g0;
    public static final v h;
    public static final v h0;
    public static final v i;
    public static final v i0;
    public static final v j;
    public static final v j0;
    public static final v k;
    public static final v k0;
    public static final v l;
    public static final v l0;
    public static final v m;
    public static final v m0;
    public static final v n;
    public static final v n0;
    public static final v o;
    public static final v o0;
    public static final v p;
    public static final v p0;
    public static final v q;
    public static final v q0;
    public static final v r;
    public static final v r0;
    public static final v s0;
    public static final v t;
    public static final v u;
    public static final v v;
    public static final v w;
    public static final v x;
    public static final v y;
    public static final v z;

    static {
        v vVar = new v("1.2.840.10045");
        f1079a = vVar;
        v b2 = vVar.b("1");
        b = b2;
        c = b2.b("1");
        v b3 = b2.b(ExifInterface.GPS_MEASUREMENT_2D);
        d = b3;
        e = b3.b("3.1");
        g = b3.b("3.2");
        h = b3.b("3.3");
        v b4 = vVar.b("4");
        i = b4;
        j = b4.b("1");
        v b5 = vVar.b(ExifInterface.GPS_MEASUREMENT_2D);
        k = b5;
        l = b5.b("1");
        v b6 = b4.b(ExifInterface.GPS_MEASUREMENT_3D);
        m = b6;
        n = b6.b("1");
        o = b6.b(ExifInterface.GPS_MEASUREMENT_2D);
        p = b6.b(ExifInterface.GPS_MEASUREMENT_3D);
        q = b6.b("4");
        v b7 = vVar.b(ExifInterface.GPS_MEASUREMENT_3D);
        r = b7;
        v b8 = b7.b("0");
        t = b8;
        u = b8.b("1");
        v = b8.b(ExifInterface.GPS_MEASUREMENT_2D);
        w = b8.b(ExifInterface.GPS_MEASUREMENT_3D);
        x = b8.b("4");
        y = b8.b("5");
        z = b8.b("6");
        B = b8.b("7");
        C = b8.b("8");
        D = b8.b("9");
        E = b8.b("10");
        F = b8.b("11");
        G = b8.b("12");
        H = b8.b("13");
        I = b8.b("14");
        J = b8.b("15");
        K = b8.b("16");
        L = b8.b("17");
        M = b8.b("18");
        N = b8.b("19");
        O = b8.b("20");
        v b9 = b7.b("1");
        P = b9;
        Q = b9.b("1");
        R = b9.b(ExifInterface.GPS_MEASUREMENT_2D);
        S = b9.b(ExifInterface.GPS_MEASUREMENT_3D);
        T = b9.b("4");
        U = b9.b("5");
        V = b9.b("6");
        W = b9.b("7");
        X = new v("1.2.840.10040.4.1");
        Y = new v("1.2.840.10040.4.3");
        v vVar2 = new v("1.3.133.16.840.63.0");
        Z = vVar2;
        a0 = vVar2.b(ExifInterface.GPS_MEASUREMENT_2D);
        b0 = vVar2.b(ExifInterface.GPS_MEASUREMENT_3D);
        c0 = vVar2.b("16");
        v vVar3 = new v("1.2.840.10046");
        d0 = vVar3;
        e0 = vVar3.b("2.1");
        v b10 = vVar3.b(ExifInterface.GPS_MEASUREMENT_3D);
        g0 = b10;
        h0 = b10.b("1");
        i0 = b10.b(ExifInterface.GPS_MEASUREMENT_2D);
        j0 = b10.b(ExifInterface.GPS_MEASUREMENT_3D);
        k0 = b10.b("4");
        l0 = b10.b("5");
        m0 = b10.b("6");
        n0 = b10.b("7");
        o0 = b10.b("8");
        v vVar4 = new v("1.3.133.16.840.9.44");
        p0 = vVar4;
        v b11 = vVar4.b("1");
        q0 = b11;
        r0 = b11.b("1");
        s0 = b11.b(ExifInterface.GPS_MEASUREMENT_2D);
    }
}
