package sdk.pendo.io.v3;

import androidx.exifinterface.media.ExifInterface;
import androidx.room.RoomMasterTable;
import sdk.pendo.io.m3.v;

/* loaded from: classes4.dex */
public interface b {
    public static final v A;
    public static final v B;
    public static final v C;
    public static final v D;
    public static final v E;
    public static final v F;
    public static final v G;
    public static final v H;
    public static final v I;
    public static final v J;
    public static final v K;
    public static final v L;
    public static final v M;
    public static final v N;
    public static final v O;
    public static final v P;
    public static final v Q;
    public static final v R;
    public static final v S;
    public static final v T;
    public static final v U;
    public static final v V;
    public static final v W;
    public static final v X;
    public static final v Y;
    public static final v Z;

    /* renamed from: a, reason: collision with root package name */
    public static final v f1677a;
    public static final v a0;
    public static final v b;
    public static final v b0;
    public static final v c;
    public static final v c0;
    public static final v d;
    public static final v d0;
    public static final v e;
    public static final v e0;
    public static final v f;
    public static final v f0;
    public static final v g;
    public static final v g0;
    public static final v h;
    public static final v h0;
    public static final v i;
    public static final v i0;
    public static final v j;
    public static final v j0;
    public static final v k;
    public static final v k0;
    public static final v l;
    public static final v l0;
    public static final v m;
    public static final v m0;
    public static final v n;
    public static final v o;
    public static final v p;
    public static final v q;
    public static final v r;
    public static final v s;
    public static final v t;
    public static final v u;
    public static final v v;
    public static final v w;
    public static final v x;
    public static final v y;
    public static final v z;

    static {
        v vVar = new v("2.16.840.1.101.3.4");
        f1677a = vVar;
        v b2 = vVar.b(ExifInterface.GPS_MEASUREMENT_2D);
        b = b2;
        c = b2.b("1");
        d = b2.b(ExifInterface.GPS_MEASUREMENT_2D);
        e = b2.b(ExifInterface.GPS_MEASUREMENT_3D);
        f = b2.b("4");
        g = b2.b("5");
        h = b2.b("6");
        i = b2.b("7");
        j = b2.b("8");
        k = b2.b("9");
        l = b2.b("10");
        m = b2.b("11");
        n = b2.b("12");
        o = b2.b("13");
        p = b2.b("14");
        q = b2.b("15");
        r = b2.b("16");
        s = b2.b("17");
        t = b2.b("18");
        u = b2.b("19");
        v = b2.b("20");
        v b3 = vVar.b("1");
        w = b3;
        x = b3.b("1");
        y = b3.b(ExifInterface.GPS_MEASUREMENT_2D);
        z = b3.b(ExifInterface.GPS_MEASUREMENT_3D);
        A = b3.b("4");
        B = b3.b("5");
        C = b3.b("6");
        D = b3.b("7");
        E = b3.b("8");
        F = b3.b("21");
        G = b3.b("22");
        H = b3.b("23");
        I = b3.b("24");
        J = b3.b("25");
        K = b3.b("26");
        L = b3.b("27");
        M = b3.b("28");
        N = b3.b("41");
        O = b3.b(RoomMasterTable.DEFAULT_ID);
        P = b3.b("43");
        Q = b3.b("44");
        R = b3.b("45");
        S = b3.b("46");
        T = b3.b("47");
        U = b3.b("48");
        v b4 = vVar.b(ExifInterface.GPS_MEASUREMENT_3D);
        V = b4;
        W = b4;
        X = b4.b("1");
        Y = b4.b(ExifInterface.GPS_MEASUREMENT_2D);
        Z = b4.b(ExifInterface.GPS_MEASUREMENT_3D);
        a0 = b4.b("4");
        b0 = b4.b("5");
        c0 = b4.b("6");
        d0 = b4.b("7");
        e0 = b4.b("8");
        f0 = b4.b("9");
        g0 = b4.b("10");
        h0 = b4.b("11");
        i0 = b4.b("12");
        j0 = b4.b("13");
        k0 = b4.b("14");
        l0 = b4.b("15");
        m0 = b4.b("16");
    }
}
