package com.google.android.gms.internal.mlkit_vision_text_common;

import com.google.firebase.encoders.FieldDescriptor;
import com.google.firebase.encoders.ObjectEncoder;
import com.google.firebase.encoders.ObjectEncoderContext;
import com.iterable.iterableapi.IterableConstants;
import java.io.IOException;

/* compiled from: com.google.android.gms:play-services-mlkit-text-recognition-common@@19.0.0 */
/* loaded from: classes3.dex */
final class zzhx implements ObjectEncoder {
    private static final FieldDescriptor zzA;
    private static final FieldDescriptor zzB;
    private static final FieldDescriptor zzC;
    private static final FieldDescriptor zzD;
    private static final FieldDescriptor zzE;
    private static final FieldDescriptor zzF;
    private static final FieldDescriptor zzG;
    private static final FieldDescriptor zzH;
    private static final FieldDescriptor zzI;
    private static final FieldDescriptor zzJ;
    private static final FieldDescriptor zzK;
    private static final FieldDescriptor zzL;
    private static final FieldDescriptor zzM;
    private static final FieldDescriptor zzN;
    private static final FieldDescriptor zzO;
    private static final FieldDescriptor zzP;
    private static final FieldDescriptor zzQ;
    private static final FieldDescriptor zzR;
    private static final FieldDescriptor zzS;
    private static final FieldDescriptor zzT;
    private static final FieldDescriptor zzU;
    private static final FieldDescriptor zzV;
    private static final FieldDescriptor zzW;
    private static final FieldDescriptor zzX;
    private static final FieldDescriptor zzY;
    private static final FieldDescriptor zzZ;
    static final zzhx zza = new zzhx();
    private static final FieldDescriptor zzaA;
    private static final FieldDescriptor zzaB;
    private static final FieldDescriptor zzaC;
    private static final FieldDescriptor zzaD;
    private static final FieldDescriptor zzaE;
    private static final FieldDescriptor zzaF;
    private static final FieldDescriptor zzaG;
    private static final FieldDescriptor zzaH;
    private static final FieldDescriptor zzaI;
    private static final FieldDescriptor zzaJ;
    private static final FieldDescriptor zzaK;
    private static final FieldDescriptor zzaL;
    private static final FieldDescriptor zzaM;
    private static final FieldDescriptor zzaN;
    private static final FieldDescriptor zzaO;
    private static final FieldDescriptor zzaP;
    private static final FieldDescriptor zzaQ;
    private static final FieldDescriptor zzaR;
    private static final FieldDescriptor zzaS;
    private static final FieldDescriptor zzaT;
    private static final FieldDescriptor zzaU;
    private static final FieldDescriptor zzaV;
    private static final FieldDescriptor zzaW;
    private static final FieldDescriptor zzaX;
    private static final FieldDescriptor zzaY;
    private static final FieldDescriptor zzaZ;
    private static final FieldDescriptor zzaa;
    private static final FieldDescriptor zzab;
    private static final FieldDescriptor zzac;
    private static final FieldDescriptor zzad;
    private static final FieldDescriptor zzae;
    private static final FieldDescriptor zzaf;
    private static final FieldDescriptor zzag;
    private static final FieldDescriptor zzah;
    private static final FieldDescriptor zzai;
    private static final FieldDescriptor zzaj;
    private static final FieldDescriptor zzak;
    private static final FieldDescriptor zzal;
    private static final FieldDescriptor zzam;
    private static final FieldDescriptor zzan;
    private static final FieldDescriptor zzao;
    private static final FieldDescriptor zzap;
    private static final FieldDescriptor zzaq;
    private static final FieldDescriptor zzar;
    private static final FieldDescriptor zzas;
    private static final FieldDescriptor zzat;
    private static final FieldDescriptor zzau;
    private static final FieldDescriptor zzav;
    private static final FieldDescriptor zzaw;
    private static final FieldDescriptor zzax;
    private static final FieldDescriptor zzay;
    private static final FieldDescriptor zzaz;
    private static final FieldDescriptor zzb;
    private static final FieldDescriptor zzc;
    private static final FieldDescriptor zzd;
    private static final FieldDescriptor zze;
    private static final FieldDescriptor zzf;
    private static final FieldDescriptor zzg;
    private static final FieldDescriptor zzh;
    private static final FieldDescriptor zzi;
    private static final FieldDescriptor zzj;
    private static final FieldDescriptor zzk;
    private static final FieldDescriptor zzl;
    private static final FieldDescriptor zzm;
    private static final FieldDescriptor zzn;
    private static final FieldDescriptor zzo;
    private static final FieldDescriptor zzp;
    private static final FieldDescriptor zzq;
    private static final FieldDescriptor zzr;
    private static final FieldDescriptor zzs;
    private static final FieldDescriptor zzt;
    private static final FieldDescriptor zzu;
    private static final FieldDescriptor zzv;
    private static final FieldDescriptor zzw;
    private static final FieldDescriptor zzx;
    private static final FieldDescriptor zzy;
    private static final FieldDescriptor zzz;

    static {
        FieldDescriptor.Builder builder = FieldDescriptor.builder("systemInfo");
        zzcw zzcwVar = new zzcw();
        zzcwVar.zza(1);
        zzb = builder.withProperty(zzcwVar.zzb()).build();
        FieldDescriptor.Builder builder2 = FieldDescriptor.builder(IterableConstants.KEY_EVENT_NAME);
        zzcw zzcwVar2 = new zzcw();
        zzcwVar2.zza(2);
        zzc = builder2.withProperty(zzcwVar2.zzb()).build();
        FieldDescriptor.Builder builder3 = FieldDescriptor.builder("isThickClient");
        zzcw zzcwVar3 = new zzcw();
        zzcwVar3.zza(37);
        zzd = builder3.withProperty(zzcwVar3.zzb()).build();
        FieldDescriptor.Builder builder4 = FieldDescriptor.builder("clientType");
        zzcw zzcwVar4 = new zzcw();
        zzcwVar4.zza(61);
        zze = builder4.withProperty(zzcwVar4.zzb()).build();
        FieldDescriptor.Builder builder5 = FieldDescriptor.builder("modelDownloadLogEvent");
        zzcw zzcwVar5 = new zzcw();
        zzcwVar5.zza(3);
        zzf = builder5.withProperty(zzcwVar5.zzb()).build();
        FieldDescriptor.Builder builder6 = FieldDescriptor.builder("customModelLoadLogEvent");
        zzcw zzcwVar6 = new zzcw();
        zzcwVar6.zza(20);
        zzg = builder6.withProperty(zzcwVar6.zzb()).build();
        FieldDescriptor.Builder builder7 = FieldDescriptor.builder("customModelInferenceLogEvent");
        zzcw zzcwVar7 = new zzcw();
        zzcwVar7.zza(4);
        zzh = builder7.withProperty(zzcwVar7.zzb()).build();
        FieldDescriptor.Builder builder8 = FieldDescriptor.builder("customModelCreateLogEvent");
        zzcw zzcwVar8 = new zzcw();
        zzcwVar8.zza(29);
        zzi = builder8.withProperty(zzcwVar8.zzb()).build();
        FieldDescriptor.Builder builder9 = FieldDescriptor.builder("onDeviceFaceDetectionLogEvent");
        zzcw zzcwVar9 = new zzcw();
        zzcwVar9.zza(5);
        zzj = builder9.withProperty(zzcwVar9.zzb()).build();
        FieldDescriptor.Builder builder10 = FieldDescriptor.builder("onDeviceFaceLoadLogEvent");
        zzcw zzcwVar10 = new zzcw();
        zzcwVar10.zza(59);
        zzk = builder10.withProperty(zzcwVar10.zzb()).build();
        FieldDescriptor.Builder builder11 = FieldDescriptor.builder("onDeviceTextDetectionLogEvent");
        zzcw zzcwVar11 = new zzcw();
        zzcwVar11.zza(6);
        zzl = builder11.withProperty(zzcwVar11.zzb()).build();
        FieldDescriptor.Builder builder12 = FieldDescriptor.builder("onDeviceTextDetectionLoadLogEvent");
        zzcw zzcwVar12 = new zzcw();
        zzcwVar12.zza(79);
        zzm = builder12.withProperty(zzcwVar12.zzb()).build();
        FieldDescriptor.Builder builder13 = FieldDescriptor.builder("onDeviceBarcodeDetectionLogEvent");
        zzcw zzcwVar13 = new zzcw();
        zzcwVar13.zza(7);
        zzn = builder13.withProperty(zzcwVar13.zzb()).build();
        FieldDescriptor.Builder builder14 = FieldDescriptor.builder("onDeviceBarcodeLoadLogEvent");
        zzcw zzcwVar14 = new zzcw();
        zzcwVar14.zza(58);
        zzo = builder14.withProperty(zzcwVar14.zzb()).build();
        FieldDescriptor.Builder builder15 = FieldDescriptor.builder("onDeviceImageLabelCreateLogEvent");
        zzcw zzcwVar15 = new zzcw();
        zzcwVar15.zza(48);
        zzp = builder15.withProperty(zzcwVar15.zzb()).build();
        FieldDescriptor.Builder builder16 = FieldDescriptor.builder("onDeviceImageLabelLoadLogEvent");
        zzcw zzcwVar16 = new zzcw();
        zzcwVar16.zza(49);
        zzq = builder16.withProperty(zzcwVar16.zzb()).build();
        FieldDescriptor.Builder builder17 = FieldDescriptor.builder("onDeviceImageLabelDetectionLogEvent");
        zzcw zzcwVar17 = new zzcw();
        zzcwVar17.zza(18);
        zzr = builder17.withProperty(zzcwVar17.zzb()).build();
        FieldDescriptor.Builder builder18 = FieldDescriptor.builder("onDeviceObjectCreateLogEvent");
        zzcw zzcwVar18 = new zzcw();
        zzcwVar18.zza(26);
        zzs = builder18.withProperty(zzcwVar18.zzb()).build();
        FieldDescriptor.Builder builder19 = FieldDescriptor.builder("onDeviceObjectLoadLogEvent");
        zzcw zzcwVar19 = new zzcw();
        zzcwVar19.zza(27);
        zzt = builder19.withProperty(zzcwVar19.zzb()).build();
        FieldDescriptor.Builder builder20 = FieldDescriptor.builder("onDeviceObjectInferenceLogEvent");
        zzcw zzcwVar20 = new zzcw();
        zzcwVar20.zza(28);
        zzu = builder20.withProperty(zzcwVar20.zzb()).build();
        FieldDescriptor.Builder builder21 = FieldDescriptor.builder("onDevicePoseDetectionLogEvent");
        zzcw zzcwVar21 = new zzcw();
        zzcwVar21.zza(44);
        zzv = builder21.withProperty(zzcwVar21.zzb()).build();
        FieldDescriptor.Builder builder22 = FieldDescriptor.builder("onDeviceSegmentationLogEvent");
        zzcw zzcwVar22 = new zzcw();
        zzcwVar22.zza(45);
        zzw = builder22.withProperty(zzcwVar22.zzb()).build();
        FieldDescriptor.Builder builder23 = FieldDescriptor.builder("onDeviceSmartReplyLogEvent");
        zzcw zzcwVar23 = new zzcw();
        zzcwVar23.zza(19);
        zzx = builder23.withProperty(zzcwVar23.zzb()).build();
        FieldDescriptor.Builder builder24 = FieldDescriptor.builder("onDeviceLanguageIdentificationLogEvent");
        zzcw zzcwVar24 = new zzcw();
        zzcwVar24.zza(21);
        zzy = builder24.withProperty(zzcwVar24.zzb()).build();
        FieldDescriptor.Builder builder25 = FieldDescriptor.builder("onDeviceTranslationLogEvent");
        zzcw zzcwVar25 = new zzcw();
        zzcwVar25.zza(22);
        zzz = builder25.withProperty(zzcwVar25.zzb()).build();
        FieldDescriptor.Builder builder26 = FieldDescriptor.builder("cloudFaceDetectionLogEvent");
        zzcw zzcwVar26 = new zzcw();
        zzcwVar26.zza(8);
        zzA = builder26.withProperty(zzcwVar26.zzb()).build();
        FieldDescriptor.Builder builder27 = FieldDescriptor.builder("cloudCropHintDetectionLogEvent");
        zzcw zzcwVar27 = new zzcw();
        zzcwVar27.zza(9);
        zzB = builder27.withProperty(zzcwVar27.zzb()).build();
        FieldDescriptor.Builder builder28 = FieldDescriptor.builder("cloudDocumentTextDetectionLogEvent");
        zzcw zzcwVar28 = new zzcw();
        zzcwVar28.zza(10);
        zzC = builder28.withProperty(zzcwVar28.zzb()).build();
        FieldDescriptor.Builder builder29 = FieldDescriptor.builder("cloudImagePropertiesDetectionLogEvent");
        zzcw zzcwVar29 = new zzcw();
        zzcwVar29.zza(11);
        zzD = builder29.withProperty(zzcwVar29.zzb()).build();
        FieldDescriptor.Builder builder30 = FieldDescriptor.builder("cloudImageLabelDetectionLogEvent");
        zzcw zzcwVar30 = new zzcw();
        zzcwVar30.zza(12);
        zzE = builder30.withProperty(zzcwVar30.zzb()).build();
        FieldDescriptor.Builder builder31 = FieldDescriptor.builder("cloudLandmarkDetectionLogEvent");
        zzcw zzcwVar31 = new zzcw();
        zzcwVar31.zza(13);
        zzF = builder31.withProperty(zzcwVar31.zzb()).build();
        FieldDescriptor.Builder builder32 = FieldDescriptor.builder("cloudLogoDetectionLogEvent");
        zzcw zzcwVar32 = new zzcw();
        zzcwVar32.zza(14);
        zzG = builder32.withProperty(zzcwVar32.zzb()).build();
        FieldDescriptor.Builder builder33 = FieldDescriptor.builder("cloudSafeSearchDetectionLogEvent");
        zzcw zzcwVar33 = new zzcw();
        zzcwVar33.zza(15);
        zzH = builder33.withProperty(zzcwVar33.zzb()).build();
        FieldDescriptor.Builder builder34 = FieldDescriptor.builder("cloudTextDetectionLogEvent");
        zzcw zzcwVar34 = new zzcw();
        zzcwVar34.zza(16);
        zzI = builder34.withProperty(zzcwVar34.zzb()).build();
        FieldDescriptor.Builder builder35 = FieldDescriptor.builder("cloudWebSearchDetectionLogEvent");
        zzcw zzcwVar35 = new zzcw();
        zzcwVar35.zza(17);
        zzJ = builder35.withProperty(zzcwVar35.zzb()).build();
        FieldDescriptor.Builder builder36 = FieldDescriptor.builder("automlImageLabelingCreateLogEvent");
        zzcw zzcwVar36 = new zzcw();
        zzcwVar36.zza(23);
        zzK = builder36.withProperty(zzcwVar36.zzb()).build();
        FieldDescriptor.Builder builder37 = FieldDescriptor.builder("automlImageLabelingLoadLogEvent");
        zzcw zzcwVar37 = new zzcw();
        zzcwVar37.zza(24);
        zzL = builder37.withProperty(zzcwVar37.zzb()).build();
        FieldDescriptor.Builder builder38 = FieldDescriptor.builder("automlImageLabelingInferenceLogEvent");
        zzcw zzcwVar38 = new zzcw();
        zzcwVar38.zza(25);
        zzM = builder38.withProperty(zzcwVar38.zzb()).build();
        FieldDescriptor.Builder builder39 = FieldDescriptor.builder("isModelDownloadedLogEvent");
        zzcw zzcwVar39 = new zzcw();
        zzcwVar39.zza(39);
        zzN = builder39.withProperty(zzcwVar39.zzb()).build();
        FieldDescriptor.Builder builder40 = FieldDescriptor.builder("deleteModelLogEvent");
        zzcw zzcwVar40 = new zzcw();
        zzcwVar40.zza(40);
        zzO = builder40.withProperty(zzcwVar40.zzb()).build();
        FieldDescriptor.Builder builder41 = FieldDescriptor.builder("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzcw zzcwVar41 = new zzcw();
        zzcwVar41.zza(30);
        zzP = builder41.withProperty(zzcwVar41.zzb()).build();
        FieldDescriptor.Builder builder42 = FieldDescriptor.builder("aggregatedCustomModelInferenceLogEvent");
        zzcw zzcwVar42 = new zzcw();
        zzcwVar42.zza(31);
        zzQ = builder42.withProperty(zzcwVar42.zzb()).build();
        FieldDescriptor.Builder builder43 = FieldDescriptor.builder("aggregatedOnDeviceFaceDetectionLogEvent");
        zzcw zzcwVar43 = new zzcw();
        zzcwVar43.zza(32);
        zzR = builder43.withProperty(zzcwVar43.zzb()).build();
        FieldDescriptor.Builder builder44 = FieldDescriptor.builder("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzcw zzcwVar44 = new zzcw();
        zzcwVar44.zza(33);
        zzS = builder44.withProperty(zzcwVar44.zzb()).build();
        FieldDescriptor.Builder builder45 = FieldDescriptor.builder("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzcw zzcwVar45 = new zzcw();
        zzcwVar45.zza(34);
        zzT = builder45.withProperty(zzcwVar45.zzb()).build();
        FieldDescriptor.Builder builder46 = FieldDescriptor.builder("aggregatedOnDeviceObjectInferenceLogEvent");
        zzcw zzcwVar46 = new zzcw();
        zzcwVar46.zza(35);
        zzU = builder46.withProperty(zzcwVar46.zzb()).build();
        FieldDescriptor.Builder builder47 = FieldDescriptor.builder("aggregatedOnDeviceTextDetectionLogEvent");
        zzcw zzcwVar47 = new zzcw();
        zzcwVar47.zza(36);
        zzV = builder47.withProperty(zzcwVar47.zzb()).build();
        FieldDescriptor.Builder builder48 = FieldDescriptor.builder("aggregatedOnDevicePoseDetectionLogEvent");
        zzcw zzcwVar48 = new zzcw();
        zzcwVar48.zza(46);
        zzW = builder48.withProperty(zzcwVar48.zzb()).build();
        FieldDescriptor.Builder builder49 = FieldDescriptor.builder("aggregatedOnDeviceSegmentationLogEvent");
        zzcw zzcwVar49 = new zzcw();
        zzcwVar49.zza(47);
        zzX = builder49.withProperty(zzcwVar49.zzb()).build();
        FieldDescriptor.Builder builder50 = FieldDescriptor.builder("pipelineAccelerationInferenceEvents");
        zzcw zzcwVar50 = new zzcw();
        zzcwVar50.zza(69);
        zzY = builder50.withProperty(zzcwVar50.zzb()).build();
        FieldDescriptor.Builder builder51 = FieldDescriptor.builder("remoteConfigLogEvent");
        zzcw zzcwVar51 = new zzcw();
        zzcwVar51.zza(42);
        zzZ = builder51.withProperty(zzcwVar51.zzb()).build();
        FieldDescriptor.Builder builder52 = FieldDescriptor.builder("inputImageConstructionLogEvent");
        zzcw zzcwVar52 = new zzcw();
        zzcwVar52.zza(50);
        zzaa = builder52.withProperty(zzcwVar52.zzb()).build();
        FieldDescriptor.Builder builder53 = FieldDescriptor.builder("leakedHandleEvent");
        zzcw zzcwVar53 = new zzcw();
        zzcwVar53.zza(51);
        zzab = builder53.withProperty(zzcwVar53.zzb()).build();
        FieldDescriptor.Builder builder54 = FieldDescriptor.builder("cameraSourceLogEvent");
        zzcw zzcwVar54 = new zzcw();
        zzcwVar54.zza(52);
        zzac = builder54.withProperty(zzcwVar54.zzb()).build();
        FieldDescriptor.Builder builder55 = FieldDescriptor.builder("imageLabelOptionalModuleLogEvent");
        zzcw zzcwVar55 = new zzcw();
        zzcwVar55.zza(53);
        zzad = builder55.withProperty(zzcwVar55.zzb()).build();
        FieldDescriptor.Builder builder56 = FieldDescriptor.builder("languageIdentificationOptionalModuleLogEvent");
        zzcw zzcwVar56 = new zzcw();
        zzcwVar56.zza(54);
        zzae = builder56.withProperty(zzcwVar56.zzb()).build();
        FieldDescriptor.Builder builder57 = FieldDescriptor.builder("faceDetectionOptionalModuleLogEvent");
        zzcw zzcwVar57 = new zzcw();
        zzcwVar57.zza(60);
        zzaf = builder57.withProperty(zzcwVar57.zzb()).build();
        FieldDescriptor.Builder builder58 = FieldDescriptor.builder("documentDetectionOptionalModuleLogEvent");
        zzcw zzcwVar58 = new zzcw();
        zzcwVar58.zza(85);
        zzag = builder58.withProperty(zzcwVar58.zzb()).build();
        FieldDescriptor.Builder builder59 = FieldDescriptor.builder("documentCroppingOptionalModuleLogEvent");
        zzcw zzcwVar59 = new zzcw();
        zzcwVar59.zza(86);
        zzah = builder59.withProperty(zzcwVar59.zzb()).build();
        FieldDescriptor.Builder builder60 = FieldDescriptor.builder("documentEnhancementOptionalModuleLogEvent");
        zzcw zzcwVar60 = new zzcw();
        zzcwVar60.zza(87);
        zzai = builder60.withProperty(zzcwVar60.zzb()).build();
        FieldDescriptor.Builder builder61 = FieldDescriptor.builder("nlClassifierOptionalModuleLogEvent");
        zzcw zzcwVar61 = new zzcw();
        zzcwVar61.zza(55);
        zzaj = builder61.withProperty(zzcwVar61.zzb()).build();
        FieldDescriptor.Builder builder62 = FieldDescriptor.builder("nlClassifierClientLibraryLogEvent");
        zzcw zzcwVar62 = new zzcw();
        zzcwVar62.zza(56);
        zzak = builder62.withProperty(zzcwVar62.zzb()).build();
        FieldDescriptor.Builder builder63 = FieldDescriptor.builder("accelerationAllowlistLogEvent");
        zzcw zzcwVar63 = new zzcw();
        zzcwVar63.zza(57);
        zzal = builder63.withProperty(zzcwVar63.zzb()).build();
        FieldDescriptor.Builder builder64 = FieldDescriptor.builder("toxicityDetectionCreateEvent");
        zzcw zzcwVar64 = new zzcw();
        zzcwVar64.zza(62);
        zzam = builder64.withProperty(zzcwVar64.zzb()).build();
        FieldDescriptor.Builder builder65 = FieldDescriptor.builder("toxicityDetectionLoadEvent");
        zzcw zzcwVar65 = new zzcw();
        zzcwVar65.zza(63);
        zzan = builder65.withProperty(zzcwVar65.zzb()).build();
        FieldDescriptor.Builder builder66 = FieldDescriptor.builder("toxicityDetectionInferenceEvent");
        zzcw zzcwVar66 = new zzcw();
        zzcwVar66.zza(64);
        zzao = builder66.withProperty(zzcwVar66.zzb()).build();
        FieldDescriptor.Builder builder67 = FieldDescriptor.builder("barcodeDetectionOptionalModuleLogEvent");
        zzcw zzcwVar67 = new zzcw();
        zzcwVar67.zza(65);
        zzap = builder67.withProperty(zzcwVar67.zzb()).build();
        FieldDescriptor.Builder builder68 = FieldDescriptor.builder("customImageLabelOptionalModuleLogEvent");
        zzcw zzcwVar68 = new zzcw();
        zzcwVar68.zza(66);
        zzaq = builder68.withProperty(zzcwVar68.zzb()).build();
        FieldDescriptor.Builder builder69 = FieldDescriptor.builder("codeScannerScanApiEvent");
        zzcw zzcwVar69 = new zzcw();
        zzcwVar69.zza(67);
        zzar = builder69.withProperty(zzcwVar69.zzb()).build();
        FieldDescriptor.Builder builder70 = FieldDescriptor.builder("codeScannerOptionalModuleEvent");
        zzcw zzcwVar70 = new zzcw();
        zzcwVar70.zza(68);
        zzas = builder70.withProperty(zzcwVar70.zzb()).build();
        FieldDescriptor.Builder builder71 = FieldDescriptor.builder("onDeviceExplicitContentCreateLogEvent");
        zzcw zzcwVar71 = new zzcw();
        zzcwVar71.zza(70);
        zzat = builder71.withProperty(zzcwVar71.zzb()).build();
        FieldDescriptor.Builder builder72 = FieldDescriptor.builder("onDeviceExplicitContentLoadLogEvent");
        zzcw zzcwVar72 = new zzcw();
        zzcwVar72.zza(71);
        zzau = builder72.withProperty(zzcwVar72.zzb()).build();
        FieldDescriptor.Builder builder73 = FieldDescriptor.builder("onDeviceExplicitContentInferenceLogEvent");
        zzcw zzcwVar73 = new zzcw();
        zzcwVar73.zza(72);
        zzav = builder73.withProperty(zzcwVar73.zzb()).build();
        FieldDescriptor.Builder builder74 = FieldDescriptor.builder("aggregatedOnDeviceExplicitContentLogEvent");
        zzcw zzcwVar74 = new zzcw();
        zzcwVar74.zza(73);
        zzaw = builder74.withProperty(zzcwVar74.zzb()).build();
        FieldDescriptor.Builder builder75 = FieldDescriptor.builder("onDeviceFaceMeshCreateLogEvent");
        zzcw zzcwVar75 = new zzcw();
        zzcwVar75.zza(74);
        zzax = builder75.withProperty(zzcwVar75.zzb()).build();
        FieldDescriptor.Builder builder76 = FieldDescriptor.builder("onDeviceFaceMeshLoadLogEvent");
        zzcw zzcwVar76 = new zzcw();
        zzcwVar76.zza(75);
        zzay = builder76.withProperty(zzcwVar76.zzb()).build();
        FieldDescriptor.Builder builder77 = FieldDescriptor.builder("onDeviceFaceMeshLogEvent");
        zzcw zzcwVar77 = new zzcw();
        zzcwVar77.zza(76);
        zzaz = builder77.withProperty(zzcwVar77.zzb()).build();
        FieldDescriptor.Builder builder78 = FieldDescriptor.builder("aggregatedOnDeviceFaceMeshLogEvent");
        zzcw zzcwVar78 = new zzcw();
        zzcwVar78.zza(77);
        zzaA = builder78.withProperty(zzcwVar78.zzb()).build();
        FieldDescriptor.Builder builder79 = FieldDescriptor.builder("smartReplyOptionalModuleLogEvent");
        zzcw zzcwVar79 = new zzcw();
        zzcwVar79.zza(78);
        zzaB = builder79.withProperty(zzcwVar79.zzb()).build();
        FieldDescriptor.Builder builder80 = FieldDescriptor.builder("textDetectionOptionalModuleLogEvent");
        zzcw zzcwVar80 = new zzcw();
        zzcwVar80.zza(80);
        zzaC = builder80.withProperty(zzcwVar80.zzb()).build();
        FieldDescriptor.Builder builder81 = FieldDescriptor.builder("onDeviceImageQualityAnalysisCreateLogEvent");
        zzcw zzcwVar81 = new zzcw();
        zzcwVar81.zza(81);
        zzaD = builder81.withProperty(zzcwVar81.zzb()).build();
        FieldDescriptor.Builder builder82 = FieldDescriptor.builder("onDeviceImageQualityAnalysisLoadLogEvent");
        zzcw zzcwVar82 = new zzcw();
        zzcwVar82.zza(82);
        zzaE = builder82.withProperty(zzcwVar82.zzb()).build();
        FieldDescriptor.Builder builder83 = FieldDescriptor.builder("onDeviceImageQualityAnalysisLogEvent");
        zzcw zzcwVar83 = new zzcw();
        zzcwVar83.zza(83);
        zzaF = builder83.withProperty(zzcwVar83.zzb()).build();
        FieldDescriptor.Builder builder84 = FieldDescriptor.builder("aggregatedOnDeviceImageQualityAnalysisLogEvent");
        zzcw zzcwVar84 = new zzcw();
        zzcwVar84.zza(84);
        zzaG = builder84.withProperty(zzcwVar84.zzb()).build();
        FieldDescriptor.Builder builder85 = FieldDescriptor.builder("imageQualityAnalysisOptionalModuleLogEvent");
        zzcw zzcwVar85 = new zzcw();
        zzcwVar85.zza(88);
        zzaH = builder85.withProperty(zzcwVar85.zzb()).build();
        FieldDescriptor.Builder builder86 = FieldDescriptor.builder("imageCaptioningOptionalModuleLogEvent");
        zzcw zzcwVar86 = new zzcw();
        zzcwVar86.zza(89);
        zzaI = builder86.withProperty(zzcwVar86.zzb()).build();
        FieldDescriptor.Builder builder87 = FieldDescriptor.builder("onDeviceImageCaptioningCreateLogEvent");
        zzcw zzcwVar87 = new zzcw();
        zzcwVar87.zza(90);
        zzaJ = builder87.withProperty(zzcwVar87.zzb()).build();
        FieldDescriptor.Builder builder88 = FieldDescriptor.builder("onDeviceImageCaptioningLoadLogEvent");
        zzcw zzcwVar88 = new zzcw();
        zzcwVar88.zza(91);
        zzaK = builder88.withProperty(zzcwVar88.zzb()).build();
        FieldDescriptor.Builder builder89 = FieldDescriptor.builder("onDeviceImageCaptioningInferenceLogEvent");
        zzcw zzcwVar89 = new zzcw();
        zzcwVar89.zza(92);
        zzaL = builder89.withProperty(zzcwVar89.zzb()).build();
        FieldDescriptor.Builder builder90 = FieldDescriptor.builder("aggregatedOnDeviceImageCaptioningInferenceLogEvent");
        zzcw zzcwVar90 = new zzcw();
        zzcwVar90.zza(93);
        zzaM = builder90.withProperty(zzcwVar90.zzb()).build();
        FieldDescriptor.Builder builder91 = FieldDescriptor.builder("onDeviceDocumentDetectionCreateLogEvent");
        zzcw zzcwVar91 = new zzcw();
        zzcwVar91.zza(94);
        zzaN = builder91.withProperty(zzcwVar91.zzb()).build();
        FieldDescriptor.Builder builder92 = FieldDescriptor.builder("onDeviceDocumentDetectionLoadLogEvent");
        zzcw zzcwVar92 = new zzcw();
        zzcwVar92.zza(95);
        zzaO = builder92.withProperty(zzcwVar92.zzb()).build();
        FieldDescriptor.Builder builder93 = FieldDescriptor.builder("onDeviceDocumentDetectionLogEvent");
        zzcw zzcwVar93 = new zzcw();
        zzcwVar93.zza(96);
        zzaP = builder93.withProperty(zzcwVar93.zzb()).build();
        FieldDescriptor.Builder builder94 = FieldDescriptor.builder("aggregatedOnDeviceDocumentDetectionLogEvent");
        zzcw zzcwVar94 = new zzcw();
        zzcwVar94.zza(97);
        zzaQ = builder94.withProperty(zzcwVar94.zzb()).build();
        FieldDescriptor.Builder builder95 = FieldDescriptor.builder("onDeviceDocumentCroppingCreateLogEvent");
        zzcw zzcwVar95 = new zzcw();
        zzcwVar95.zza(98);
        zzaR = builder95.withProperty(zzcwVar95.zzb()).build();
        FieldDescriptor.Builder builder96 = FieldDescriptor.builder("onDeviceDocumentCroppingLoadLogEvent");
        zzcw zzcwVar96 = new zzcw();
        zzcwVar96.zza(99);
        zzaS = builder96.withProperty(zzcwVar96.zzb()).build();
        FieldDescriptor.Builder builder97 = FieldDescriptor.builder("onDeviceDocumentCroppingLogEvent");
        zzcw zzcwVar97 = new zzcw();
        zzcwVar97.zza(100);
        zzaT = builder97.withProperty(zzcwVar97.zzb()).build();
        FieldDescriptor.Builder builder98 = FieldDescriptor.builder("aggregatedOnDeviceDocumentCroppingLogEvent");
        zzcw zzcwVar98 = new zzcw();
        zzcwVar98.zza(101);
        zzaU = builder98.withProperty(zzcwVar98.zzb()).build();
        FieldDescriptor.Builder builder99 = FieldDescriptor.builder("onDeviceDocumentEnhancementCreateLogEvent");
        zzcw zzcwVar99 = new zzcw();
        zzcwVar99.zza(102);
        zzaV = builder99.withProperty(zzcwVar99.zzb()).build();
        FieldDescriptor.Builder builder100 = FieldDescriptor.builder("onDeviceDocumentEnhancementLoadLogEvent");
        zzcw zzcwVar100 = new zzcw();
        zzcwVar100.zza(103);
        zzaW = builder100.withProperty(zzcwVar100.zzb()).build();
        FieldDescriptor.Builder builder101 = FieldDescriptor.builder("onDeviceDocumentEnhancementLogEvent");
        zzcw zzcwVar101 = new zzcw();
        zzcwVar101.zza(104);
        zzaX = builder101.withProperty(zzcwVar101.zzb()).build();
        FieldDescriptor.Builder builder102 = FieldDescriptor.builder("aggregatedOnDeviceDocumentEnhancementLogEvent");
        zzcw zzcwVar102 = new zzcw();
        zzcwVar102.zza(105);
        zzaY = builder102.withProperty(zzcwVar102.zzb()).build();
        FieldDescriptor.Builder builder103 = FieldDescriptor.builder("scannerAutoZoomEvent");
        zzcw zzcwVar103 = new zzcw();
        zzcwVar103.zza(106);
        zzaZ = builder103.withProperty(zzcwVar103.zzb()).build();
    }

    private zzhx() {
    }

    @Override // com.google.firebase.encoders.Encoder
    public final /* bridge */ /* synthetic */ void encode(Object obj, ObjectEncoderContext objectEncoderContext) throws IOException {
        zzmz zzmzVar = (zzmz) obj;
        ObjectEncoderContext objectEncoderContext2 = objectEncoderContext;
        objectEncoderContext2.add(zzb, zzmzVar.zzf());
        objectEncoderContext2.add(zzc, zzmzVar.zzc());
        objectEncoderContext2.add(zzd, (Object) null);
        objectEncoderContext2.add(zze, zzmzVar.zzb());
        objectEncoderContext2.add(zzf, (Object) null);
        objectEncoderContext2.add(zzg, (Object) null);
        objectEncoderContext2.add(zzh, (Object) null);
        objectEncoderContext2.add(zzi, (Object) null);
        objectEncoderContext2.add(zzj, (Object) null);
        objectEncoderContext2.add(zzk, (Object) null);
        objectEncoderContext2.add(zzl, zzmzVar.zze());
        objectEncoderContext2.add(zzm, zzmzVar.zzd());
        objectEncoderContext2.add(zzn, (Object) null);
        objectEncoderContext2.add(zzo, (Object) null);
        objectEncoderContext2.add(zzp, (Object) null);
        objectEncoderContext2.add(zzq, (Object) null);
        objectEncoderContext2.add(zzr, (Object) null);
        objectEncoderContext2.add(zzs, (Object) null);
        objectEncoderContext2.add(zzt, (Object) null);
        objectEncoderContext2.add(zzu, (Object) null);
        objectEncoderContext2.add(zzv, (Object) null);
        objectEncoderContext2.add(zzw, (Object) null);
        objectEncoderContext2.add(zzx, (Object) null);
        objectEncoderContext2.add(zzy, (Object) null);
        objectEncoderContext2.add(zzz, (Object) null);
        objectEncoderContext2.add(zzA, (Object) null);
        objectEncoderContext2.add(zzB, (Object) null);
        objectEncoderContext2.add(zzC, (Object) null);
        objectEncoderContext2.add(zzD, (Object) null);
        objectEncoderContext2.add(zzE, (Object) null);
        objectEncoderContext2.add(zzF, (Object) null);
        objectEncoderContext2.add(zzG, (Object) null);
        objectEncoderContext2.add(zzH, (Object) null);
        objectEncoderContext2.add(zzI, (Object) null);
        objectEncoderContext2.add(zzJ, (Object) null);
        objectEncoderContext2.add(zzK, (Object) null);
        objectEncoderContext2.add(zzL, (Object) null);
        objectEncoderContext2.add(zzM, (Object) null);
        objectEncoderContext2.add(zzN, (Object) null);
        objectEncoderContext2.add(zzO, (Object) null);
        objectEncoderContext2.add(zzP, (Object) null);
        objectEncoderContext2.add(zzQ, (Object) null);
        objectEncoderContext2.add(zzR, (Object) null);
        objectEncoderContext2.add(zzS, (Object) null);
        objectEncoderContext2.add(zzT, (Object) null);
        objectEncoderContext2.add(zzU, (Object) null);
        objectEncoderContext2.add(zzV, zzmzVar.zza());
        objectEncoderContext2.add(zzW, (Object) null);
        objectEncoderContext2.add(zzX, (Object) null);
        objectEncoderContext2.add(zzY, (Object) null);
        objectEncoderContext2.add(zzZ, (Object) null);
        objectEncoderContext2.add(zzaa, (Object) null);
        objectEncoderContext2.add(zzab, (Object) null);
        objectEncoderContext2.add(zzac, (Object) null);
        objectEncoderContext2.add(zzad, (Object) null);
        objectEncoderContext2.add(zzae, (Object) null);
        objectEncoderContext2.add(zzaf, (Object) null);
        objectEncoderContext2.add(zzag, (Object) null);
        objectEncoderContext2.add(zzah, (Object) null);
        objectEncoderContext2.add(zzai, (Object) null);
        objectEncoderContext2.add(zzaj, (Object) null);
        objectEncoderContext2.add(zzak, (Object) null);
        objectEncoderContext2.add(zzal, (Object) null);
        objectEncoderContext2.add(zzam, (Object) null);
        objectEncoderContext2.add(zzan, (Object) null);
        objectEncoderContext2.add(zzao, (Object) null);
        objectEncoderContext2.add(zzap, (Object) null);
        objectEncoderContext2.add(zzaq, (Object) null);
        objectEncoderContext2.add(zzar, (Object) null);
        objectEncoderContext2.add(zzas, (Object) null);
        objectEncoderContext2.add(zzat, (Object) null);
        objectEncoderContext2.add(zzau, (Object) null);
        objectEncoderContext2.add(zzav, (Object) null);
        objectEncoderContext2.add(zzaw, (Object) null);
        objectEncoderContext2.add(zzax, (Object) null);
        objectEncoderContext2.add(zzay, (Object) null);
        objectEncoderContext2.add(zzaz, (Object) null);
        objectEncoderContext2.add(zzaA, (Object) null);
        objectEncoderContext2.add(zzaB, (Object) null);
        objectEncoderContext2.add(zzaC, (Object) null);
        objectEncoderContext2.add(zzaD, (Object) null);
        objectEncoderContext2.add(zzaE, (Object) null);
        objectEncoderContext2.add(zzaF, (Object) null);
        objectEncoderContext2.add(zzaG, (Object) null);
        objectEncoderContext2.add(zzaH, (Object) null);
        objectEncoderContext2.add(zzaI, (Object) null);
        objectEncoderContext2.add(zzaJ, (Object) null);
        objectEncoderContext2.add(zzaK, (Object) null);
        objectEncoderContext2.add(zzaL, (Object) null);
        objectEncoderContext2.add(zzaM, (Object) null);
        objectEncoderContext2.add(zzaN, (Object) null);
        objectEncoderContext2.add(zzaO, (Object) null);
        objectEncoderContext2.add(zzaP, (Object) null);
        objectEncoderContext2.add(zzaQ, (Object) null);
        objectEncoderContext2.add(zzaR, (Object) null);
        objectEncoderContext2.add(zzaS, (Object) null);
        objectEncoderContext2.add(zzaT, (Object) null);
        objectEncoderContext2.add(zzaU, (Object) null);
        objectEncoderContext2.add(zzaV, (Object) null);
        objectEncoderContext2.add(zzaW, (Object) null);
        objectEncoderContext2.add(zzaX, (Object) null);
        objectEncoderContext2.add(zzaY, (Object) null);
        objectEncoderContext2.add(zzaZ, (Object) null);
    }
}
